In [19]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('RECIFE.CSV', delimiter=';', skiprows=8, encoding='latin1')

In [3]:
df.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2020/01/01,0000 UTC,0,"1011,8","1011,9","1011,1",NaN,"27,5","21,6","27,5","27,4","21,6","21,5",71.0,70.0,71.0,NaN,NaN,NaN,NaN
1,2020/01/01,0100 UTC,0,"1011,9","1011,9","1011,7",NaN,"27,1","21,4","27,5","27,1","21,6","21,2",71.0,68.0,71.0,NaN,NaN,NaN,NaN
2,2020/01/01,0200 UTC,0,"1011,8",1012,"1011,8",NaN,27,"21,7","27,3",27,"21,7","21,4",73.0,71.0,73.0,NaN,NaN,NaN,NaN
3,2020/01/01,0300 UTC,0,"1011,5","1011,8","1011,5",NaN,"26,4","21,9",27,"26,4",22,"21,7",77.0,73.0,77.0,NaN,NaN,NaN,NaN
4,2020/01/01,0400 UTC,",8","1010,6","1011,5","1010,6",NaN,"24,5","22,1","26,4","24,5","22,4","21,7",87.0,77.0,87.0,NaN,NaN,NaN,NaN

In [26]:
coluna_temperatura_maxima = df['TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)']

In [27]:
coluna_temperatura_maxima = pd.to_numeric(df['TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)'], errors='coerce')

In [6]:

coluna_temperatura_maxima.mean()

np.float64(26.881506090808415)

In [7]:
coluna_temperatura_maxima.head()

0     NaN
1     NaN
2     NaN
3    27.0
4     NaN
Name: TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C), dtype: float64

In [8]:
df.isnull()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,True,True
1,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,True,True
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,True,True
3,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8780,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8781,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8782,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
8783,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True

In [23]:

df_radiacao = df['RADIACAO GLOBAL (Kj/m²)']
print(f'Qtd de nulos na coluna radiacao: {df_radiacao.isnull().sum()}')

Qtd de nulos na coluna radiacao: 3989

In [24]:
df_radiacao_sem_null = df_radiacao.dropna()
print(f'Qtd de nulos após remoção: {df_radiacao_sem_null.isnull().sum()}')

Qtd de nulos após remoção: 0

In [25]:
df_amostra = df[['RADIACAO GLOBAL (Kj/m²)','TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)','TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)']].sample(1000)
df_amostra

,RADIACAO GLOBAL (Kj/m²),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
7225,NaN,"26,6","26,5"
5239,NaN,"23,8","22,9"
1265,"1583,8","31,5",30
3262,NaN,"25,1","24,6"
2349,"16,2","28,5","27,5"
...,...,...,...
5277,10,24,"22,5"
45,"82,2","28,7","27,8"
3978,"1926,7","29,3","27,7"
1371,NaN,28,"27,3"
7970,NaN,"26,2","25,9"